name: Azure Static Web Apps CD

on:
  pull_request:
    branches: [ main ]
env:
  API_URL: 'https://shopping-list-back.azurewebsites.net/api/v1'
jobs:
#  e2e_tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js 18.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.x
#          cache: 'npm'
#      - run: npm ci
#      - run: npm run build
#      - name: Run tests
#        run: npm run cypress:headless

  build_and_deploy_job:
#    needs: e2e_tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_BUSH_05FB25610 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "target/dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env: # Add environment variables here
          API_URL: https://shopping-list-back.azurewebsites.net/api/v1

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_BUSH_05FB25610 }}
          action: "close"
